import type { AccountRole } from "@/lib/auth/roles";
import type { InteractiveMessagePayload } from "@/lib/whatsapp/interactive";

export type {
  InteractiveMessagePayload,
  InteractiveButtonsPayload,
  InteractiveListPayload,
  InteractiveButton,
  InteractiveListRow,
  InteractiveListSection,
} from "@/lib/whatsapp/interactive";

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  created_at: string;
  updated_at: string;
}

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, "owner">;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  phone: string;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  name?: string;
  email?: string;
  company?: string;
  avatar_url?: string;
  /** True for a WhatsApp group — `phone` is the group JID's digits,
   *  not a real phone number. */
  is_group?: boolean;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed `contact_tags(tags(*))` (e.g. the
   *  Inbox conversation list, for tag filtering). Absent otherwise. */
  tags?: Tag[];
}

export interface Tag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  created_at: string;
  /** Auto-managed by the platform (e.g. "Grupo") — hidden from the
   *  regular tag manager and from tag-based reports. */
  isSystem?: boolean;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

export interface CustomField {
  id: string;
  user_id: string;
  /** Tenancy key — NOT NULL since migration 017. */
  account_id: string;
  field_name: string;
  field_type: string;
  field_options?: Record<string, unknown>;
  created_at: string;
}

export interface ContactCustomValue {
  id: string;
  contact_id: string;
  custom_field_id: string;
  value?: string;
}

export interface ContactNote {
  id: string;
  contact_id: string;
  user_id: string | null;
  note_text: string;
  created_at: string;
  /** Author's display name — null if the user was deleted. */
  author_name?: string | null;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

export interface Conversation {
  id: string;
  user_id: string;
  contact_id: string;
  status: ConversationStatus;
  assigned_agent_id?: string;
  department_id?: string | null;
  last_message_text?: string;
  last_message_at?: string;
  unread_count: number;
  created_at: string;
  updated_at: string;
  contact?: Contact;
  /**
   * AI auto-reply state for this thread (migration 029 + 033):
   *  - `ai_autoreply_disabled` — the bot is paused here (a human took
   *    over, or the model handed off). Sticky until re-enabled.
   *  - `ai_reply_count` — how many times the bot has auto-replied,
   *    checked against the account's per-conversation cap.
   *  - `ai_handoff_summary` — short internal note the bot wrote when it
   *    handed off, shown to whoever takes the thread over.
   */
  ai_autoreply_disabled?: boolean;
  ai_reply_count?: number;
  ai_handoff_summary?: string | null;
  /** The contact's product/service tags — e.g. [Setor Gráfico],
   *  [Fardamentos] — shown as colored chips in the conversation list. */
  tags?: Tag[];
  /** True when the current assignee hasn't confirmed starting service
   *  after a transfer or a business-hours auto-resume — drives the
   *  "iniciar atendimento / apenas visualizar" pop-up. */
  needs_acknowledgment?: boolean;
  acknowledgment_reason?: "transferred" | "resumed";
  paused_at?: string;
  pause_reason?: "manual" | "business_hours";
}

// ============================================================
// Notifications (migration 027)
// ============================================================

export type NotificationType = 'conversation_assigned';

export interface Notification {
  id: string;
  account_id: string;
  /** Recipient — the agent this notification is for. */
  user_id: string;
  type: NotificationType;
  conversation_id?: string;
  contact_id?: string;
  /** Who triggered it. Null when an automation/system assigned it. */
  actor_user_id?: string;
  title: string;
  body?: string;
  read_at?: string;
  created_at: string;
}

export type SenderType = 'customer' | 'agent' | 'bot';
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive';
export type MessageStatus = 'sending' | 'sent' | 'delivered' | 'read' | 'failed';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  sender_id?: string;
  /** Sending agent's display name — only meaningful when sender_type
   *  is "agent". Used for the small "sent by X" label audio/video
   *  bubbles show (see message-bubble.tsx); other content types carry
   *  the sender's identity in the bold signature text itself instead. */
  sender_name?: string;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  template_name?: string;
  message_id?: string;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
  /**
   * Structured payload of an OUTBOUND interactive message (reply
   * buttons or list) we sent. Lets the thread re-render the buttons /
   * rows, not just the body text. Only set when `content_type ===
   * 'interactive'` and `sender_type` is agent/bot. Migration 035.
   */
  interactive_payload?: InteractiveMessagePayload;
  /**
   * True when the AI auto-reply bot generated + sent this message (as
   * opposed to a human agent or a deterministic Flow/automation send,
   * which all share `sender_type='bot'`/`'agent'`). Drives the "AI"
   * badge in the inbox. Migration 033.
   */
  ai_generated?: boolean;
  /** Set once this message was "deleted for everyone" — by the agent
   *  who sent it, or by the customer revoking their own message. The
   *  bubble shows a "Mensagem apagada" placeholder instead of the
   *  real content when this is present. */
  deleted_at?: string;
  /** Set when an agent edited their own already-sent text within the
   *  edit window — drives the "(editado)" badge. */
  edited_at?: string;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  phone_number_id: string;
  waba_id?: string;
  access_token: string;
  verify_token?: string;
  status: 'connected' | 'disconnected';
  connected_at?: string;
  /**
   * Set when POST /{phone_number_id}/register last succeeded. NULL
   * means the number was saved but never actually subscribed for
   * webhooks on Meta's side — inbound events will be silently lost.
   */
  registered_at?: string;
  /** Set when POST /{waba_id}/subscribed_apps last succeeded. */
  subscribed_apps_at?: string;
  /** Last error from /register; cleared on success. */
  last_registration_error?: string;
}

// Raw Meta status enum. We persist this verbatim from Meta (sync + webhook)
// rather than collapsing to a local TitleCase set — distinctions like
// PAUSED vs DISABLED vs IN_APPEAL drive the edit/resubmit/delete flows.
// DRAFT is the local-only state before the row is submitted to Meta.
export type MessageTemplateStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED'
  | 'PAUSED'
  | 'DISABLED'
  | 'IN_APPEAL'
  | 'PENDING_DELETION';

export type TemplateButton =
  | { type: 'QUICK_REPLY'; text: string }
  | { type: 'URL'; text: string; url: string; example?: string }
  | { type: 'PHONE_NUMBER'; text: string; phone_number: string }
  | { type: 'COPY_CODE'; text: string; example: string };

export interface TemplateSampleValues {
  body?: string[];
  header?: string[];
}

export interface MessageTemplate {
  id: string;
  user_id: string;
  name: string;
  category: 'Marketing' | 'Utility' | 'Authentication';
  language?: string;
  header_type?: 'text' | 'image' | 'video' | 'document';
  header_content?: string;
  header_handle?: string;
  header_media_url?: string;
  body_text: string;
  footer_text?: string;
  buttons?: TemplateButton[];
  sample_values?: TemplateSampleValues;
  status?: MessageTemplateStatus;
  meta_template_id?: string;
  rejection_reason?: string;
  quality_score?: 'GREEN' | 'YELLOW' | 'RED';
  submission_error?: string;
  last_submitted_at?: string;
  created_at: string;
}


export type BroadcastStatus = 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
export type RecipientStatus = 'pending' | 'sent' | 'delivered' | 'read' | 'replied' | 'failed';

/**
 * Fatia 3: no more `template_name`/`template_language`/
 * `template_variables` — those were Meta Cloud API-only concepts and
 * the product now sends plain text/media straight through UAZAPI (see
 * src/lib/whatsapp/uazapi-client.ts, no template approval step).
 * Field names are camelCase to match the Drizzle row shape returned
 * by /api/broadcasts/* (see src/db/schema.ts `broadcasts`).
 */
export interface Broadcast {
  id: string;
  accountId: string;
  userId: string | null;
  name: string;
  contentText: string;
  mediaUrl: string | null;
  /** `{ tagIds?: string[] }` — empty/absent tagIds means "all contacts". */
  audienceFilter?: { tagIds?: string[] } | null;
  scheduledAt?: string | null;
  status: BroadcastStatus;
  totalRecipients: number;
  sentCount: number;
  deliveredCount: number;
  readCount: number;
  repliedCount: number;
  failedCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface BroadcastRecipient {
  id: string;
  broadcastId: string;
  contactId: string;
  status: RecipientStatus;
  sentAt?: string | null;
  deliveredAt?: string | null;
  readAt?: string | null;
  repliedAt?: string | null;
  errorMessage?: string | null;
  /**
   * UAZAPI's message id, persisted when the send succeeds so a future
   * status webhook can mirror delivered/read back onto this row.
   */
  whatsappMessageId?: string | null;
  createdAt: string;
  /** Hydrated by GET /api/broadcasts/[id] (joined with contacts). */
  contact?: { name: string | null; phone: string | null };
}


// ============================================================
// Quick replies — reusable snippets (migration 035)
// ============================================================

export type QuickReplyKind = 'text' | 'interactive';

export interface QuickReply {
  id: string;
  /** Account tenancy key — shared across all members of the account. */
  account_id: string;
  /** Author / audit only. */
  user_id: string;
  title: string;
  /** Trigger keyword for the composer's "/" popover, e.g. "pix" ->
   *  typing "/pix" filters straight to this reply. No leading slash
   *  stored — the slash is only the UI trigger. */
  shortcut?: string | null;
  kind: QuickReplyKind;
  /** Set when `kind === 'text'`. */
  content_text?: string | null;
  /** Set when `kind === 'interactive'`. */
  interactive_payload?: InteractiveMessagePayload | null;
  created_at: string;
  updated_at: string;
}
